// Generated by CoffeeScript 2.5.1
(function() {
  // Register the plugin
  var path;

  path = require('path');

  module.exports = function() {
    if (process.env.DISABLE_BUKWILD_CREDITS === 'true') {
      return;
    }
    return this.addPlugin({
      src: path.resolve(__dirname, 'plugin.js'),
      mode: 'client'
    });
  };

  // Export meta for Nuxt
  module.exports.meta = require('../package.json');

}).call(this);
